version: "3.3"
services:
  simple-gateway:
    image: lupino/simple-gateway:latest
    container_name: simple-gateway
    restart: always
    depends_on:
    - hack-editor
    ports:
    - "3000:3000"
    volumes:
    - ./simple-gateway.yml:/etc/simple-gateway.yml
  hack-editor:
    image: lupino/hack-editor:latest
    container_name: hack-editor
    restart: always
    environment:
    - LC_ALL=en_US.UTF-8
    volumes:
    - ../source:/data
